name: BuildImage Docker and push to Docker Hub and deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4
    
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21
        
    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pubonline-app:latest
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install npm dependencies
        run: npm install
      - name: Run build project
        run: npm run build --if-present
      - name: Deploy to AWS EC2 Instance
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            EXCLUDE: "/dist/, /node_modules/"
    
  
    
      
