name: BuildImage Docker and push to Docker Hub and deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4
    
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21
        
    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pubonline-app:latest

  deploy:
    needs: build-docker-image
    runs-on: self-hosted
    steps:

      - name: Pull image API from docker hub
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pubonline-app:latest

      - name: Remove docker container rformaggini/pubonline-app
        run: sudo docker rm -f pubonline-app

      - name: Run docker container
        run: sudo docker run -d -p 80:80 --name pubonline-app ${{ secrets.DOCKERHUB_USERNAME }}/pubonline-app
    
  
    
      
