name: Deploy on DEVELOP and BuildImage Docker

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21
        
    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pubonline-app:latest

      
