name: BuildImage Docker Deploy on DEVELOP

on:
  push:
    branches: [ "master" ]
    
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4
    
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21
        
    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pubonline-app:latest
    
    - uses: actions/checkout@v4
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PUBONLINE_APP }}
        projectId: pubonline-app
  
    
      
